//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock_Management_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductNote
    {
        public int pn_id { get; set; }
        public string product_note { get; set; }
        public string description { get; set; }
        public bool status { get; set; }
    }
}
