//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock_Management_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int st_id { get; set; }
        public int spl_id { get; set; }
        public int pro_id { get; set; }
        public int pn_id { get; set; }
        public int qty { get; set; }
        public decimal price { get; set; }
        public System.DateTime input_date { get; set; }
    }
}
