//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock_Management_System.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int spl_id { get; set; }
        public string spl_name { get; set; }
        public System.DateTime input_date { get; set; }
        public bool status { get; set; }
    }
}
